---
- name: Apply roles
  hosts: managed
  become: true
  pre_tasks:
    - name: pre_tasks message
      debug:
        msg: 'Ensure web server configuration.'
  roles:
    - role: quiz-roles

  post_tasks:
    - name: post_tasks message
      debug:
        msg: 'Web server is configured.'
